### ISSUE TITLE
xrdb in the sx script doesn't work

### ISSUE THREAD

**Issue by tleydxdy** [Earnestly/sx#14]
In my ~/.config/Xresources file I have
```
Xft.dpi: 192
```
and in my sx file I have
```
xrdb -merge ~/.config/Xresources
```
However the dpi is not set on start. running the command manually after start will correctly set the dpi

**Comment by Earnestly** [comment]
Neither `sx` nor `startx` do anything which would be responsible for this.  When I was using `startx` long ago I also used to experience similar issues with `-merge` which is why as a result I started using `-load` instead. E.g. https://github.com/Earnestly/dotfiles/blob/master/local/cfg/sx/sxrc#L5

There may be interactions with daemons such as `gnome-settings-daemon` which sets various resources in the `RESOURCE_MANAGER`, overriding `xrdb`.  You can perhaps try `xprop -root -spy RESOURCE_MANAGER` to monitor for changes and try determine what's going on.

**Comment by tleydxdy** [comment]
turns out it was xwallpaper that was resetting it. I moved the merge after that and it works now.
