### ISSUE TITLE
Run xinitrc.d startup scripts

### ISSUE THREAD

**Issue by bennetthardwick** [Earnestly/sx#18]
Some packages install startup scripts to `/etc/X11/xinit/xinitrc.d/` and it seems that currently they are not being run by `sx`. 

For example, on Arch systemd services get the DISPLAY environment variable set in one of these hooks: 
https://wiki.archlinux.org/index.php/Systemd/User#DISPLAY_and_XAUTHORITY

**Comment by Earnestly** [comment]
You will need to source them as from `sxrc` or however you want to use them.  `sx` itself won't be involved with `xinit`'s infrasturcture.

**Comment by eli-schwartz** [comment]
> and it seems that currently they are not being run by `sx`.

They aren't run by startx either.

... unless you copied the example xinitrc, including the block that loads these, for your own ~/.xinitrc. See https://wiki.archlinux.org/index.php/Xinit#xinitrc

(I'm not going to pretend that people actually execute startx and *deliberately* let it fall back to using /etc/X11/xinit/xinitrc because twm is not actually something people use.)

**Comment by bennetthardwick** [comment]
> They aren't run by startx either.

Ah thanks, I would have run into the exact same issue if I was using startx :facepalm:
