### ISSUE TITLE
gnome-keyring's ssh agent doesn't work

### ISSUE THREAD

**Issue by tleydxdy** [Earnestly/sx#6]
Starting i3 with config for gnome-keyring according to [ArchWiki](https://wiki.archlinux.org/index.php/GNOME/Keyring#xinitrc_method)
```
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
```
startx works fine, but not sx.
Using sx still shows:
```
sign_and_send_pubkey: signing failed: agent refused operation
```

**Comment by Earnestly** [comment]
Can you elaborate on what exactly you've done?  The wiki article discusses `.xinitrc` which `sx` doesn't use.

**Comment by tleydxdy** [comment]
that's what I thought. I was adding those config in .config/sx/sxrc, after it didn't work, I copied it to .xinitrc and tried startx and things worked fine. tbh the only reason I could think of is that DISPLAY is 1 instead of 0.

**Comment by Earnestly** [comment]
Trying to reason about this and why you might get a permission error is leading me to think of the authority file.  Since `sx` doesn't use the de facto location of `HOME/.Xauthority` try including `XAUTHORITY` along with `DISPLAY` in your `dbus-update-activation-environment` command, e.g.:

```
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY
```

I'll try to understand this issue in the mean time if that doesn't work.

**Comment by tleydxdy** [comment]
that actually worked, thanks!

**Comment by Earnestly** [comment]
Oh nice, thanks for the follow up.  This also means I don't have to do anything \o/.

I'll update the wiki article as well to mention the need for potential need for `XAUTHORITY`.
